-- ═══════════════════════════════════════════════════════════
--  Interview Reports schema
--  Stores per-question code snapshots + AI-generated analysis.
-- ═══════════════════════════════════════════════════════════

-- ── Code snapshots ────────────────────────────────────────
-- Captures the candidate's final code for each question at
-- the moment they advance or the session ends.
create table if not exists code_snapshots (
  id            uuid primary key default gen_random_uuid(),
  session_id    uuid not null references sessions(id) on delete cascade,
  order_index   int  not null,
  problem_id    text not null,
  category      text not null,
  code          text not null default '',
  language      text not null default 'python',
  hints_used    int  not null default 0,
  -- Serialised array of { role, content, timestamp } AI chat messages
  ai_messages   jsonb not null default '[]',
  created_at    timestamptz default now(),
  unique(session_id, order_index)
);

-- ── Interview reports ─────────────────────────────────────
-- One report per session, generated by the AI after the session ends.
create table if not exists interview_reports (
  id                    uuid primary key default gen_random_uuid(),
  session_id            uuid not null references sessions(id) on delete cascade unique,
  -- pending | generating | completed | failed
  status                text not null default 'pending',
  overall_summary       text,
  strengths             jsonb,   -- string[]
  areas_for_improvement jsonb,   -- string[]
  -- Array of per-question objects (see report.ts for shape)
  per_question          jsonb,
  ai_use_score          int,     -- 1–10
  ai_use_notes          text,
  error_message         text,
  generated_at          timestamptz,
  created_at            timestamptz default now()
);

-- ── Row Level Security ────────────────────────────────────
alter table code_snapshots   enable row level security;
alter table interview_reports enable row level security;

-- Only the interviewer who owns the session can read/write snapshots
create policy "Interviewer can manage snapshots"
  on code_snapshots for all
  using (
    exists (
      select 1 from sessions s
      where s.id = code_snapshots.session_id
        and s.interviewer_id = auth.uid()
    )
  );

-- Only the interviewer can read their reports
create policy "Interviewer can view own reports"
  on interview_reports for all
  using (
    exists (
      select 1 from sessions s
      where s.id = interview_reports.session_id
        and s.interviewer_id = auth.uid()
    )
  );
